/* ============================================================
   人类学思想史 — 文献与地理元数据
   ------------------------------------------------------------
   homes : 人物所在城市 [经度, 纬度]（主要任教/研究机构所在地）
   sites : 田野点/研究区域 [名称, 经度, 纬度]
   works : 观点 id → 原始书名/篇名（英文或原文）
   说明：坐标为近似值，用于地图示意；扶手椅学者没有任何田野点，
         这一"空白"本身就是人类学史的一部分。
   ============================================================ */
window.ANTHRO_META = {

  homes: {
    bastian: [13.40, 52.52], tylor: [-1.26, 51.75], morgan: [-77.61, 43.16],
    frazer: [0.12, 52.21], boas: [-74.01, 40.71], durkheim: [2.35, 48.86],
    mauss: [2.35, 48.86], malinowski: [-0.13, 51.51], "radcliffe-brown": [-1.26, 51.75],
    sapir: [-87.63, 41.88], mead: [-74.01, 40.71], benedict: [-74.01, 40.71],
    whorf: [-72.69, 41.77], "evans-pritchard": [-1.26, 51.75], firth: [-0.13, 51.51],
    fortes: [0.12, 52.21], bateson: [0.12, 52.21], "levy-strauss": [2.35, 48.86],
    leach: [0.12, 52.21], gluckman: [-2.24, 53.48], turner: [-2.24, 53.48],
    douglas: [-0.13, 51.51], geertz: [-87.63, 41.88], dumont: [2.35, 48.86],
    sahlins: [-87.63, 41.88], wolf: [-74.01, 40.71], mintz: [-76.61, 39.29],
    harris: [-74.01, 40.71], schneider: [-87.63, 41.88], bourdieu: [2.35, 48.86],
    rubin: [-83.74, 42.28], ortner: [-74.01, 40.71], "rosaldo-m": [-122.17, 37.43],
    taussig: [-74.01, 40.71], fabian: [4.90, 52.37], asad: [-0.34, 53.77],
    clifford: [-122.03, 36.97], marcus: [-95.37, 29.76], appadurai: [-87.63, 41.88],
    strathern: [0.12, 52.21], descola: [2.35, 48.86], viveiros: [-43.17, -22.91],
    latour: [2.35, 48.86], tsing: [-122.03, 36.97], "abu-lughod": [-74.01, 40.71],
    obeyesekere: [-74.66, 40.35], freeman: [149.13, -35.28], fei: [116.41, 39.90],
    lin: [116.41, 39.90], yan: [-118.24, 34.05], childe: [-3.19, 55.95],
    binford: [-106.65, 35.08], hodder: [0.12, 52.21], washburn: [-122.27, 37.87],
    montagu: [-74.66, 40.35], lewontin: [-71.11, 42.37], goodall: [0.12, 52.21],
    dewaal: [-84.39, 33.75], kleinman: [-71.06, 42.36],
    "ingold": [-2.09, 57.15],
    "de-la-cadena": [-121.74, 38.54],
    "kohn": [-73.57, 45.5],
    "haraway": [-122.03, 36.97],
    "wagner": [-78.48, 38.03],
    "rosaldo-r": [-122.17, 37.43],
    "willis": [-1.9, 52.48],
    "das": [77.21, 28.61],
    "fassin": [2.35, 48.86],
    "herzfeld": [-71.11, 42.37],
    "gupta": [-118.24, 34.05],
    "trouillot": [-87.63, 41.88],
    "newton": [-74.01, 40.71],
    "stoler": [-74.01, 40.71],
    "miller-d": [-0.13, 51.51],
    "boellstorff": [-117.83, 33.68],
    "coleman": [-73.57, 45.5],
    "lock": [-73.57, 45.5],
    "martin-e": [-74.01, 40.71],
    "luhrmann": [-122.17, 37.43],
    "farmer": [-71.06, 42.36],
    "hrdy": [-121.74, 38.54],
    "paabo": [12.39, 51.34],
    "leakey-m": [-1.29, 36.82],
    "cann": [-157.86, 21.31],
    "flannery": [-83.74, 42.28],
    "behar": [-83.74, 42.28],
    "wang-mingming": [116.41, 39.9],
    "xiang-biao": [-1.26, 51.75],
    "jing-jun": [116.41, 39.9],
    "zhuang-kongshao": [120.16, 30.27]
  },

  cities: {
    "-74.01,40.71": "纽约", "0.12,52.21": "剑桥", "2.35,48.86": "巴黎", "-87.63,41.88": "芝加哥",
    "-1.26,51.75": "牛津", "-0.13,51.51": "伦敦", "-2.24,53.48": "曼彻斯特", "-122.03,36.97": "圣克鲁兹",
    "-74.66,40.35": "普林斯顿", "116.41,39.90": "北京", "13.40,52.52": "柏林", "-77.61,43.16": "罗切斯特",
    "-72.69,41.77": "哈特福德", "-76.61,39.29": "巴尔的摩", "-83.74,42.28": "安娜堡", "-122.17,37.43": "斯坦福",
    "4.90,52.37": "阿姆斯特丹", "-0.34,53.77": "赫尔", "-95.37,29.76": "休斯顿", "-43.17,-22.91": "里约热内卢",
    "149.13,-35.28": "堪培拉", "-118.24,34.05": "洛杉矶", "-3.19,55.95": "爱丁堡", "-106.65,35.08": "阿尔伯克基",
    "-122.27,37.87": "伯克利", "-71.11,42.37": "剑桥（麻省）", "-84.39,33.75": "亚特兰大", "-71.06,42.36": "波士顿"
  ,
    "-2.09,57.15": "阿伯丁",
    "-121.74,38.54": "戴维斯",
    "-73.57,45.50": "蒙特利尔",
    "-78.48,38.03": "夏洛茨维尔",
    "77.21,28.61": "德里",
    "-1.90,52.48": "伯明翰"
  ,
    "-117.83,33.68": "尔湾",
    "12.39,51.34": "莱比锡",
    "-1.29,36.82": "内罗毕",
    "-157.86,21.31": "檀香山",
    "120.16,30.27": "杭州"
  },

  sites: {
    bastian: [["秘鲁（考察）", -77.0, -12.0], ["东南亚（旅行考察）", 100.5, 13.7]],
    tylor: [["墨西哥（旅行考察）", -99.13, 19.43]],
    morgan: [["易洛魁领地（纽约州）", -76.4, 42.9]],
    frazer: [],
    boas: [["巴芬岛", -64.5, 66.0], ["夸扣特尔（温哥华岛）", -127.4, 50.6]],
    durkheim: [["澳大利亚原住民（文献研究）", 133.9, -23.7]],
    mauss: [["毛利与萨摩亚民族志（文献研究）", 172.0, -40.0]],
    malinowski: [["特罗布里恩德群岛", 150.7, -8.6]],
    "radcliffe-brown": [["安达曼群岛", 92.7, 12.5], ["西澳大利亚", 122.0, -25.0]],
    sapir: [["努特卡（温哥华岛）", -126.0, 50.0], ["黑脚（阿尔伯塔）", -113.0, 54.0]],
    mead: [["萨摩亚", -171.8, -14.0], ["阿德默勒尔蒂群岛", 147.0, -2.0], ["巴厘岛", 115.2, -8.4]],
    benedict: [["祖尼（普韦布洛）", -108.8, 35.1], ["日本（远距研究）", 139.7, 35.7]],
    whorf: [["霍皮人（美国西南）", -110.6, 35.9]],
    "evans-pritchard": [["阿赞德（苏丹南部）", 27.5, 5.0], ["努尔兰（南苏丹）", 32.0, 9.0]],
    firth: [["蒂科皮亚岛", 168.8, -12.3]],
    fortes: [["塔伦西（加纳北部）", -0.8, 10.7]],
    bateson: [["塞皮克河（新几内亚）", 143.5, -4.2], ["巴厘岛", 115.2, -8.4]],
    "levy-strauss": [["纳姆比克瓦拉/波洛罗（巴西内陆）", -56.0, -13.5]],
    leach: [["克钦山地（缅甸）", 97.5, 25.5], ["斯里兰卡（旱区）", 80.7, 7.9]],
    gluckman: [["祖鲁兰（南非）", 31.0, -28.5], ["巴罗策兰（赞比亚）", 23.1, -15.3]],
    turner: [["恩丹布（赞比亚）", 24.5, -11.5]],
    douglas: [["莱莱人（刚果）", 22.5, -5.0]],
    geertz: [["爪哇", 110.4, -7.5], ["巴厘岛", 115.2, -8.4], ["舍夫沙万（摩洛哥）", -5.27, 35.17]],
    dumont: [["南印度（泰米尔地区）", 78.5, 10.8]],
    sahlins: [["斐济", 178.4, -17.8], ["夏威夷", -157.9, 21.3], ["库克群岛", -159.8, -21.2]],
    wolf: [["瓦哈卡（墨西哥）", -96.7, 17.1], ["南蒂罗尔（阿尔卑斯）", 11.3, 46.5]],
    mintz: [["波多黎各", -66.5, 18.2], ["海地", -72.3, 18.5]],
    harris: [["巴伊亚（巴西）", -38.5, -13.0], ["莫桑比克", 35.0, -19.0], ["印度（文献研究）", 78.0, 20.0]],
    schneider: [["雅浦岛", 138.1, 9.5]],
    bourdieu: [["卡比利亚（阿尔及利亚）", 5.07, 36.75], ["贝阿恩（法国西南）", -0.37, 43.3]],
    rubin: [],
    ortner: [["昆布（尼泊尔）", 86.7, 27.8], ["夏威夷", -157.9, 21.3]],
    "rosaldo-m": [["伊隆戈（菲律宾吕宋）", 121.2, 16.5]],
    taussig: [["考卡河谷（哥伦比亚）", -76.5, 3.4]],
    fabian: [["加丹加（刚果）", 27.5, -10.5]],
    asad: [["卡巴比亚（苏丹）", 28.0, 15.6]],
    clifford: [],
    marcus: [["汤加", -175.2, -21.2]],
    appadurai: [["孟买", 72.9, 19.1], ["南印度（宗教研究）", 78.5, 10.8]],
    strathern: [["哈根山（巴布亚新几内亚）", 144.2, -5.85]],
    descola: [["阿丘雅（厄瓜多尔）", -77.9, -2.6]],
    viveiros: [["阿劳埃特（帕拉州）", -51.5, -5.0], ["上黑河（亚马逊）", -66.0, 0.5]],
    latour: [["阿比让（科特迪瓦）", -4.0, 6.8], ["索尔克研究所（拉霍亚）", -117.25, 32.85]],
    tsing: [["南加里曼丹（印尼）", 114.5, -2.5], ["俄勒冈森林", -122.7, 44.0]],
    "abu-lughod": [["西部沙漠（埃及贝都因）", 27.2, 31.35]],
    obeyesekere: [["康提（斯里兰卡）", 80.6, 7.3]],
    freeman: [["萨摩亚", -171.8, -14.0], ["沙捞越（伊班人）", 112.0, 2.0]],
    fei: [["开弦弓村（江苏吴江）", 120.6, 31.2], ["禄村（云南）", 102.0, 25.0]],
    lin: [["黄村（福建古田）", 118.7, 26.6], ["凉山（四川）", 102.3, 27.9]],
    yan: [["下岬村（黑龙江）", 126.5, 46.5]],
    childe: [["斯卡拉布雷（苏格兰）", -3.34, 59.05], ["近东新石器遗址（比较研究）", 43.0, 36.3]],
    binford: [["阿纳克图沃克山口（阿拉斯加）", -151.7, 68.1], ["多尔多涅（法国）", 0.9, 44.85]],
    hodder: [["恰塔霍裕克（土耳其）", 32.83, 37.67], ["伊尔查穆斯（肯尼亚）", 36.0, 0.3]],
    washburn: [["非洲（推动灵长类野外研究）", 36.0, -1.5]],
    montagu: [],
    lewontin: [],
    goodall: [["贡贝溪（坦桑尼亚）", 29.63, -4.67]],
    dewaal: [["伯格斯动物园（阿纳姆）", 5.9, 51.99], ["耶基斯田野站（亚特兰大）", -84.0, 33.9]],
    kleinman: [["台北", 121.5, 25.05], ["长沙（湖南医学院）", 113.0, 28.2]],
    "ingold": [["芬兰北部（萨米地区）", 26.0, 68.0]],
    "de-la-cadena": [["秘鲁安第斯（库斯科）", -71.97, -13.53]],
    "kohn": [["厄瓜多尔阿维拉（纳波河）", -77.0, -1.0]],
    "wagner": [["巴布亚新几内亚（达里比）", 143.5, -6.3]],
    "rosaldo-r": [["菲律宾吕宋（伊隆戈）", 121.3, 16.5]],
    "willis": [["英国汉默镇（工业区）", -1.9, 52.48]],
    "das": [["印度德里", 77.21, 28.61], ["旁遮普（分治记忆）", 75.0, 31.0]],
    "fassin": [["法国（城市执法）", 2.35, 48.86], ["南非（艾滋病政策）", 28.05, -26.2]],
    "herzfeld": [["希腊克里特（雷西姆农）", 24.47, 35.37], ["曼谷", 100.5, 13.75]],
    "gupta": [["印度北部（官僚与贫困）", 80.0, 26.5]],
    "trouillot": [["海地", -72.34, 18.54]],
    "newton": [["美国（纽约、火岛樱桃林）", -73.0, 40.75]],
    "stoler": [["印尼（苏门答腊种植园）", 101.0, 0.5]],
    "miller-d": [["特立尼达", -61.5, 10.5], ["伦敦（数字与物质文化）", -0.13, 51.51], ["印度（消费研究）", 77.21, 28.61]],
    "boellstorff": [["印尼", 106.85, -6.2], ["虚拟世界（Second Life）", -122.0, 37.0]],
    "coleman": [["线上（自由软件与 Anonymous）", -74.0, 40.7]],
    "lock": [["日本（京都）", 135.77, 35.01], ["北美（更年期比较研究）", -73.57, 45.5]],
    "martin-e": [["美国（更年期与免疫研究）", -76.61, 39.29]],
    "luhrmann": [["美国（福音派教会）", -87.63, 41.88], ["加纳", -0.19, 5.6], ["印度", 80.27, 13.08]],
    "farmer": [["海地（中央高原）", -72.0, 19.0], ["卢旺达", 30.06, -1.94], ["秘鲁（卡拉瓦亚）", -73.0, -13.0]],
    "hrdy": [["印度（阿布山的长尾叶猴）", 72.7, 24.6]],
    "paabo": [["西伯利亚（丹尼索瓦洞）", 86.0, 51.4]],
    "leakey-m": [["坦桑尼亚奥杜威峡谷", 35.4, -2.98], ["莱托利", 35.2, -3.0]],
    "cann": [["实验室（全球人群样本）", -157.86, 21.31]],
    "flannery": [["近东（扎格罗斯山地）", 48.0, 33.0], ["墨西哥瓦哈卡", -96.7, 17.06]],
    "behar": [["墨西哥（圣路易斯波托西）", -100.98, 22.15], ["古巴（哈瓦那）", -82.38, 23.13]],
    "wang-mingming": [["福建溪村", 118.5, 24.9]],
    "xiang-biao": [["北京“浙江村”", 116.41, 39.9], ["印度（IT 劳工）", 77.21, 28.61]],
    "jing-jun": [["甘肃大川", 103.5, 36.1]],
    "zhuang-kongshao": [["福建黄村", 119.0, 26.5]]
  },

  works: {
    "bastian-psychic": "Der Mensch in der Geschichte",
    "bastian-museum": "Museum für Völkerkunde, Berlin",
    "tylor-culture": "Primitive Culture", "tylor-animism": "Primitive Culture", "tylor-survivals": "Primitive Culture",
    "morgan-stages": "Ancient Society",
    "morgan-kinterms": "Systems of Consanguinity and Affinity of the Human Family",
    "morgan-iroquois": "League of the Ho-dé-no-sau-nee, or Iroquois",
    "frazer-goldengod": "The Golden Bough", "frazer-king": "The Golden Bough",
    "boas-relativism": "The Mind of Primitive Man",
    "boas-historism": "The Limitations of the Comparative Method of Anthropology",
    "boas-fieldwork": "The Methods of Ethnology",
    "boas-fourfields": "The History of Anthropology",
    "durkheim-rules": "Les Règles de la méthode sociologique",
    "durkheim-elementary": "Les Formes élémentaires de la vie religieuse",
    "mauss-gift": "Essai sur le don",
    "mauss-body": "Les Techniques du corps",
    "mauss-sacrifice": "Essai sur la nature et la fonction du sacrifice",
    "malinowski-method": "Argonauts of the Western Pacific",
    "malinowski-functionalism": "Argonauts of the Western Pacific",
    "malinowski-kula": "Argonauts of the Western Pacific",
    "malinowski-crime": "Crime and Custom in Savage Society",
    "radcliffe-brown-structure": "The Andaman Islanders",
    "radcliffe-brown-joking": "On Joking Relationships",
    "radcliffe-brown-function": "Structure and Function in Primitive Society",
    "sapir-language": "Language",
    "sapir-culture": "Culture, Genuine and Spurious",
    "mead-samoa": "Coming of Age in Samoa",
    "mead-gender": "Sex and Temperament in Three Primitive Societies",
    "benedict-patterns": "Patterns of Culture", "benedict-apollonian": "Patterns of Culture",
    "benedict-chrysanthemum": "The Chrysanthemum and the Sword",
    "whorf-relativity": "Science and Linguistics",
    "whorf-thought": "Languages and Logic",
    "evans-pritchard-witchcraft": "Witchcraft, Oracles and Magic among the Azande",
    "evans-pritchard-nuer": "The Nuer",
    "evans-pritchard-history": "Social Anthropology (Marett Lecture)",
    "firth-process": "We, the Tikopia",
    "firth-economy": "Primitive Polynesian Economy",
    "fortes-politics": "African Political Systems",
    "fortes-tallensi": "The Web of Kinship among the Tallensi",
    "bateson-schismogenesis": "Naven",
    "bateson-bali": "Balinese Character",
    "bateson-mind": "Steps to an Ecology of Mind",
    "levy-strauss-alliance": "Les Structures élémentaires de la parenté",
    "levy-strauss-tristes": "Tristes Tropiques",
    "levy-strauss-savage": "La Pensée sauvage",
    "levy-strauss-myth": "Mythologiques I: Le Cru et le cuit",
    "levy-strauss-race": "Race et histoire",
    "leach-burma": "Political Systems of Highland Burma",
    "leach-rethink": "Rethinking Anthropology",
    "gluckman-rebellion": "Rituals of Rebellion in South-East Africa",
    "gluckman-judicial": "The Judicial Process among the Barotse of Northern Rhodesia",
    "turner-ritual": "Schism and Continuity in an African Society",
    "turner-symbols": "The Forest of Symbols",
    "turner-communitas": "The Ritual Process",
    "douglas-purity": "Purity and Danger",
    "douglas-grid": "Natural Symbols",
    "geertz-interpretation": "The Interpretation of Cultures",
    "geertz-deep": "Deep Play: Notes on the Balinese Cockfight",
    "geertz-involution": "Agricultural Involution",
    "geertz-religion": "Religion as a Cultural System",
    "geertz-negara": "Negara: The Theatre State in Nineteenth-Century Bali",
    "dumont-homo": "Homo Hierarchicus", "dumont-ideology": "Homo Hierarchicus",
    "sahlins-affluent": "Stone Age Economics",
    "sahlins-practical-reason": "Culture and Practical Reason",
    "sahlins-islands": "Islands of History",
    "wolf-community": "Anthropology",
    "wolf-history": "Europe and the People Without History",
    "wolf-power": "Europe and the People Without History",
    "mintz-worker": "Worker in the Cane",
    "mintz-sugar": "Sweetness and Power", "mintz-commodity": "Sweetness and Power",
    "harris-theory": "The Rise of Anthropological Theory",
    "harris-materialism": "Cultural Materialism",
    "harris-cows": "Cows, Pigs, Wars and Witches",
    "schneider-american": "American Kinship: A Cultural Account",
    "schneider-critique": "A Critique of the Study of Kinship",
    "bourdieu-habitus": "Esquisse d'une théorie de la pratique",
    "bourdieu-distinction": "La Distinction",
    "rubin-traffic": "The Traffic in Women",
    "rubin-sex": "Thinking Sex",
    "ortner-nature": "Is Female to Male as Nature Is to Culture?",
    "ortner-practice": "Theory in Anthropology since the Sixties",
    "rosaldo-passion": "Knowledge and Passion",
    "rosaldo-feminism": "The Use and Abuse of Anthropology",
    "taussig-devil": "The Devil and Commodity Fetishism in South America",
    "taussig-mimesis": "Mimesis and Alterity",
    "fabian-time": "Time and the Other",
    "asad-encounter": "Anthropology and the Colonial Encounter",
    "asad-genealogy": "Genealogies of Religion",
    "clifford-authority": "On Ethnographic Authority",
    "clifford-predicament": "The Predicament of Culture",
    "marcus-multisited": "Ethnography in/of the World System",
    "marcus-authority": "Writing Culture",
    "appadurai-things": "The Social Life of Things",
    "appadurai-global": "Modernity at Large", "appadurai-imagined": "Modernity at Large",
    "strathern-gift": "The Gender of the Gift",
    "strathern-nature": "After Nature",
    "descola-ontology": "Par-delà nature et culture",
    "descola-naturalism": "Par-delà nature et culture",
    "viveiros-perspectivism": "Cosmological Deixis and Amerindian Perspectivism",
    "viveiros-multispecies": "Métaphysiques cannibales",
    "latour-lab": "Laboratory Life",
    "latour-modern": "Nous n'avons jamais été modernes",
    "latour-actors": "Pandora's Hope",
    "tsing-friction": "Friction",
    "tsing-mushroom": "The Mushroom at the End of the World",
    "abu-poetry": "Veiled Sentiments",
    "abu-writing": "Writing Against Culture",
    "obeyesekere-cook": "The Apotheosis of Captain Cook",
    "freeman-revisit": "Margaret Mead and Samoa: The Making and Unmaking of an Anthropological Myth",
    "fei-peasant": "Peasant Life in China",
    "fei-chaxu": "From the Soil", "fei-ritual": "From the Soil",
    "fei-multiunity": "The Plurality and Unity of the Chinese Nation",
    "lin-golden": "The Golden Wing",
    "lin-lolo": "The Lolo of Liang Shan",
    "yan-gift": "The Flow of Gifts",
    "yan-private": "Private Life under Socialism",
    "childe-neolithic": "Man Makes Himself",
    "childe-culturehistory": "The Dawn of European Civilization",
    "binford-science": "Archaeology as Anthropology",
    "binford-midrange": "For Theory Building in Archaeology",
    "hodder-symbolic": "Symbols in Action",
    "hodder-reading": "Reading the Past",
    "washburn-newphys": "The New Physical Anthropology",
    "washburn-primate": "The New Physical Anthropology",
    "montagu-myth": "Man's Most Dangerous Myth: The Fallacy of Race",
    "montagu-unesco": "UNESCO Statement on Race",
    "lewontin-apportionment": "The Apportionment of Human Diversity",
    "lewontin-genes": "Not in Our Genes",
    "goodall-tools": "In the Shadow of Man",
    "goodall-gombe": "The Chimpanzees of Gombe",
    "dewaal-politics": "Chimpanzee Politics",
    "dewaal-morality": "Good Natured",
    "kleinman-models": "Patients and Healers in the Context of Culture",
    "kleinman-narratives": "The Illness Narratives"
  ,
    "levy-strauss-structural-anth": "Anthropologie structurale",
    "levy-strauss-totemism": "Le Totémisme aujourd'hui"
  ,
    "bastian-vokergedanken": "Grundzüge der Ethnologie",
    "bastian-diffusion": "Die Völker des östlichen Asien"
  ,
    "tylor-early-history": "Researches into the Early History of Mankind",
    "tylor-adhesion": "On a Method of Investigating the Development of Institutions"
  ,
    "morgan-house": "Houses and House-Life of the American Aborigines",
    "morgan-civitas": "Ancient Society"
  ,
    "frazer-totemism": "Totemism",
    "frazer-magic-religion": "The Golden Bough (3rd ed.)"
  ,
    "boas-immigrant-headform": "Changes in Bodily Form of Descendants of Immigrants",
    "boas-kwakiutl": "The Social Organization of the Kwakiutl"
  ,
    "durkheim-division": "De la division du travail social",
    "durkheim-suicide": "Le Suicide"
  ,
    "mauss-person": "Une catégorie de l'esprit humain : la notion de personne",
    "mauss-eskimo": "Essai sur les variations saisonnières des sociétés Eskimos"
  ,
    "malinowski-magic": "Magic, Science and Religion",
    "malinowski-sex-family": "The Sexual Life of Savages"
  ,
    "radcliffe-brown-socialstructure": "On Social Structure",
    "radcliffe-brown-totemism": "The Sociological Theory of Totemism"
  ,
    "sapir-environment": "Language and Environment",
    "sapir-status": "The Status of Linguistics as a Science"
  ,
    "mead-newguinea": "Growing Up in New Guinea",
    "mead-male-female": "Male and Female"
  ,
    "benedict-race": "Race: Science and Politics",
    "benedict-zuni": "Zuni Mythology"
  ,
    "whorf-hopi-time": "An American Indian Model of the Universe",
    "whorf-cryptotypes": "Grammatical Categories"
  ,
    "ep-nuer-time": "The Nuer",
    "ep-sanusi": "The Sanusi of Cyrenaica",
    "ep-nuer-religion": "Nuer Religion"
  ,
    "firth-organization": "Elements of Social Organization",
    "firth-ritual": "Tikopia Ritual and Belief"
  ,
    "fortes-descent": "The Structure of Unilineal Descent Groups",
    "fortes-ancestors": "Oedipus and Job in West African Religion"
  ,
    "bateson-double-bind": "Toward a Theory of Schizophrenia",
    "bateson-mind-nature": "Mind and Nature: A Necessary Unity"
  ,
    "leach-pul-eliya": "Pul Eliya: A Village in Ceylon",
    "leach-genesis": "Genesis as Myth"
  ,
    "gluckman-situational": "Analysis of a Social Situation in Modern Zululand",
    "gluckman-conflict": "Order and Rebellion in Tribal Africa"
  ,
    "turner-social-drama": "Dramas, Fields, and Metaphors",
    "turner-pilgrimage": "Image and Pilgrimage in Christian Culture"
  ,
    "douglas-risk": "Risk and Culture",
    "douglas-institutions": "How Institutions Think"
  ,
    "geertz-local-knowledge": "Local Knowledge",
    "geertz-works-lives": "Works and Lives: The Anthropologist as Author"
  ,
    "dumont-individualism": "Essais sur l'individualisme"
  ,
    "sahlins-historical-metaphors": "Historical Metaphors and Mythical Realities",
    "sahlins-kinship": "What Kinship Is — And Is Not"
  ,
    "wolf-peasant-wars": "Peasant Wars of the Twentieth Century",
    "wolf-envisioning": "Envisioning Power"
  ,
    "mintz-caribbean": "Caribbean Transformations",
    "mintz-afro-american": "An Anthropological Approach to the Afro-American Past"
  ,
    "harris-sacred-cattle": "The Cultural Ecology of India's Sacred Cattle",
    "harris-cannibals": "Cannibals and Kings"
  ,
    "schneider-blood-law": "American Kinship: A Cultural Account"
  ,
    "bourdieu-reproduction": "La Reproduction",
    "bourdieu-sense": "Le Sens pratique",
    "bourdieu-masculine": "La Domination masculine"
  ,
    "rubin-charmed-circle": "Thinking Sex",
    "rubin-deviations": "Deviations: A Gayle Rubin Reader"
  ,
    "ortner-sherpas": "Sherpas through their Rituals",
    "ortner-everest": "Life and Death on Mt. Everest",
    "ortner-subjectivity": "Subjectivity and Cultural Critique"
  ,
    "rosaldo-woman-culture": "Woman, Culture, and Society",
    "rosaldo-self": "Toward an Anthropology of Self and Feeling"
  ,
    "taussig-shamanism": "Shamanism, Colonialism, and the Wild Man",
    "taussig-defacement": "Defacement"
  ,
    "fabian-denial": "Time and the Other",
    "fabian-language": "Language and Colonial Power"
  ,
    "asad-islam": "The Idea of an Anthropology of Islam",
    "asad-secular": "Formations of the Secular"
  ,
    "clifford-salvage": "Of Other Peoples: Beyond the Salvage Paradigm",
    "clifford-routes": "Routes: Travel and Translation in the Late Twentieth Century"
  ,
    "marcus-cultural-critique": "Anthropology as Cultural Critique",
    "marcus-contemporary": "Designs for an Anthropology of the Contemporary"
  ,
    "appadurai-aspiration": "The Capacity to Aspire",
    "appadurai-future": "The Future as Cultural Fact"
  ,
    "strathern-women-in-between": "Women in Between",
    "strathern-audit": "Audit Cultures"
  ,
    "descola-spears": "Les lances du crépuscule",
    "descola-ecology": "L'écologie des autres"
  ,
    "viveiros-soul": "A inconstância da alma selvagem"
  ,
    "latour-irreductions": "Irréductions",
    "latour-reassembling": "Reassembling the Social",
    "latour-gaia": "Face à Gaïa"
  ,
    "tsing-diamond-queen": "In the Realm of the Diamond Queen",
    "tsing-feral-atlas": "Feral Atlas"
  ,
    "abu-muslim-women": "Do Muslim Women Need Saving?",
    "abu-dramas": "Dramas of Nationhood"
  ,
    "obeyesekere-medusa": "Medusa's Hair",
    "obeyesekere-work": "The Work of Culture"
  ,
    "freeman-hoaxing": "The Fateful Hoaxing of Margaret Mead"
  ,
    "fei-reproduction": "生育制度",
    "fei-small-town": "小城镇大问题",
    "fei-cultural-awareness": "反思·对话·文化自觉"
  ,
    "lin-ancestors": "Under the Ancestors' Shadow"
  ,
    "yan-individualization": "The Individualization of Chinese Society"
  ,
    "childe-danube": "The Danube in Prehistory",
    "childe-urban-revolution": "The Urban Revolution",
    "childe-social-evolution": "Social Evolution"
  ,
    "binford-nunamiut": "Nunamiut Ethnoarchaeology",
    "binford-bones": "Bones: Ancient Men and Modern Myths"
  ,
    "hodder-domestication": "The Domestication of Europe",
    "hodder-entangled": "Entangled"
  ,
    "washburn-hunting": "The Evolution of Hunting"
  ,
    "montagu-concept-race": "The Concept of Race",
    "montagu-touching": "Touching: The Human Significance of the Skin"
  ,
    "lewontin-spandrels": "The Spandrels of San Marco",
    "lewontin-ideology": "Biology as Ideology"
  ,
    "goodall-window": "Through a Window",
    "goodall-hope": "Reason for Hope"
  ,
    "dewaal-bonobo": "Bonobo: The Forgotten Ape",
    "dewaal-empathy": "The Age of Empathy"
  ,
    "kleinman-neurasthenia": "Social Origins of Distress and Disease",
    "kleinman-social-suffering": "Social Suffering",
    "kleinman-caregiving": "The Soul of Care"
  ,
    "ingold-dwelling": "The Perception of the Environment",
    "ingold-hunters-pastoralists": "Hunters, Pastoralists and Ranchers",
    "ingold-lines": "Lines: A Brief History",
    "ingold-making": "Making: Anthropology, Archaeology, Art and Architecture",
    "cadena-earth-beings": "Earth Beings: Ecologies of Practice across Andean Worlds",
    "cadena-cosmopolitics": "Indigenous Cosmopolitics in the Andes",
    "cadena-partial-connections": "Earth Beings: Ecologies of Practice across Andean Worlds",
    "kohn-dogs": "How Dogs Dream: Amazonian Natures and the Politics of Transspecies Engagement",
    "kohn-forest": "How Forests Think: Toward an Anthropology beyond the Human",
    "haraway-cyborg": "A Cyborg Manifesto",
    "haraway-situated": "Situated Knowledges",
    "haraway-companion": "The Companion Species Manifesto",
    "haraway-staying": "Staying with the Trouble",
    "wagner-daribi": "Habu: The Innovation of Meaning in Daribi Religion",
    "wagner-invention": "The Invention of Culture",
    "wagner-symbols": "Symbols that Stand for Themselves",
    "rosaldo-r-ilongot": "Ilongot Headhunting, 1883-1974",
    "rosaldo-r-grief": "Grief and a Headhunter's Rage",
    "rosaldo-r-culture-truth": "Culture and Truth",
    "willis-learning": "Learning to Labour",
    "willis-ethnographic-imagination": "The Ethnographic Imagination",
    "das-critical-events": "Critical Events",
    "das-violence": "Life and Words",
    "das-violence-subjectivity": "Violence and Subjectivity",
    "fassin-trauma": "L'Empire du traumatisme",
    "fassin-police": "La Force de l'ordre",
    "fassin-moral": "A Companion to Moral Anthropology",
    "herzfeld-poetics": "The Poetics of Manhood",
    "herzfeld-indifference": "The Social Production of Indifference",
    "herzfeld-intimacy": "Cultural Intimacy",
    "gupta-state": "Blurred Boundaries",
    "gupta-anthropology-of-state": "Anthropology of the State: A Reader",
    "gupta-red-tape": "Red Tape",
    "trouillot-haiti": "Haiti: State Against Nation",
    "trouillot-silencing": "Silencing the Past",
    "trouillot-global": "Global Transformations",
    "newton-mother-camp": "Mother Camp: Female Impersonators in America",
    "newton-cherry-grove": "Cherry Grove, Fire Island",
    "newton-butch": "My Butch Career",
    "stoler-intimacies": "Carnal Knowledge and Imperial Power",
    "stoler-archives": "Along the Archival Grain",
    "stoler-duress": "Duress: Imperial Durabilities in Our Times",
    "miller-things": "Material Culture and Mass Consumption",
    "miller-stuff": "Stuff",
    "miller-tales-facebook": "Tales from Facebook",
    "miller-social-media": "How the World Changed Social Media",
    "boellstorff-archipelago": "The Gay Archipelago",
    "boellstorff-second-life": "Coming of Age in Second Life",
    "boellstorff-methods": "Ethnography and Virtual Worlds",
    "coleman-coding-freedom": "Coding Freedom",
    "coleman-anonymous": "Hacker, Hoaxer, Whistleblower, Spy",
    "lock-local-biology": "Encounters with Aging",
    "lock-twice-dead": "Twice Dead",
    "lock-biomedicine": "An Anthropology of Biomedicine",
    "martin-woman-body": "The Woman in the Body",
    "martin-immune": "Flexible Bodies",
    "luhrmann-persuasion": "Persuasions of the Witch's Craft",
    "luhrmann-mind": "Of Two Minds",
    "luhrmann-when-god-talks-back": "When God Talks Back",
    "luhrmann-how-god-becomes-real": "How God Becomes Real",
    "farmer-aids": "AIDS and Accusation",
    "farmer-violence": "An Anthropology of Structural Violence",
    "farmer-pathologies": "Pathologies of Power",
    "hrdy-woman": "The Woman That Never Evolved",
    "hrdy-mother-nature": "Mother Nature",
    "hrdy-mothers-others": "Mothers and Others",
    "paabo-ancient-dna": "Neandertal DNA sequences and the origin of modern humans",
    "paabo-denisova": "The complete mitochondrial genome of an extinct hominin",
    "paabo-neanderthal-man": "Neanderthal Man: In Search of Lost Genomes",
    "leakey-olduvai": "Olduvai Gorge: My Search for Early Man",
    "leakey-laetoli": "Pliocene footprints in the Laetolil Beds at Laetoli",
    "cann-mitochondrial-eve": "Mitochondrial DNA and human evolution",
    "cann-molecular-clock": "Mitochondrial DNA and human evolution",
    "flannery-broad-spectrum": "Origins and Ecological Effects of Early Domestication in Iran and the Near East",
    "flannery-mesoamerican-village": "The Early Mesoamerican Village",
    "behar-translated-woman": "Translated Woman",
    "behar-vulnerable-observer": "The Vulnerable Observer",
    "xiang-zhejiangcun": "Transcending Boundaries: Zhejiangcun",
    "xiang-body-shopping": "Global \"Body Shopping\"",
    "xiang-nearby": "附近的消失",
    "xiang-self-as-method": "把自己作为方法"
  ,
    "fei-reproduction": "生育制度",
    "fei-small-town": "小城镇大问题",
    "fei-cultural-awareness": "反思·对话·文化自觉",
    "yan-individualization": "The Individualization of Chinese Society",
    "lin-ancestors": "Under the Ancestors' Shadow",
    "childe-urban-revolution": "The Urban Revolution",
    "childe-social-evolution": "Social Evolution",
    "childe-danube": "The Danube in Prehistory",
    "binford-nunamiut": "Nunamiut Ethnoarchaeology",
    "binford-bones": "Bones: Ancient Men and Modern Myths",
    "hodder-domestication": "The Domestication of Europe",
    "hodder-entangled": "Entangled",
    "washburn-hunting": "The Evolution of Hunting",
    "montagu-concept-race": "The Concept of Race",
    "montagu-touching": "Touching: The Human Significance of the Skin",
    "lewontin-spandrels": "The Spandrels of San Marco",
    "lewontin-ideology": "Biology as Ideology",
    "goodall-window": "Through a Window",
    "goodall-hope": "Reason for Hope",
    "dewaal-bonobo": "Bonobo: The Forgotten Ape",
    "dewaal-empathy": "The Age of Empathy",
    "kleinman-neurasthenia": "Social Origins of Distress and Disease",
    "kleinman-social-suffering": "Social Suffering",
    "kleinman-caregiving": "The Soul of Care"
  }
};
