/* ============================================================
   人类学思想史 — 文献与地理元数据
   ------------------------------------------------------------
   homes : 人物所在城市 [经度, 纬度]（主要任教/研究机构所在地）
   sites : 田野点/研究区域 [名称, 经度, 纬度]
   works : 观点 id → 原始书名/篇名（英文或原文）
   说明：坐标为近似值，用于地图示意；扶手椅学者没有任何田野点，
         这一"空白"本身就是人类学史的一部分。
   ============================================================ */
window.ANTHRO_META = {

  homes: {
    bastian: [13.40, 52.52], tylor: [-1.26, 51.75], morgan: [-77.61, 43.16],
    frazer: [0.12, 52.21], boas: [-74.01, 40.71], durkheim: [2.35, 48.86],
    mauss: [2.35, 48.86], malinowski: [-0.13, 51.51], "radcliffe-brown": [-1.26, 51.75],
    sapir: [-87.63, 41.88], mead: [-74.01, 40.71], benedict: [-74.01, 40.71],
    whorf: [-72.69, 41.77], "evans-pritchard": [-1.26, 51.75], firth: [-0.13, 51.51],
    fortes: [0.12, 52.21], bateson: [0.12, 52.21], "levy-strauss": [2.35, 48.86],
    leach: [0.12, 52.21], gluckman: [-2.24, 53.48], turner: [-2.24, 53.48],
    douglas: [-0.13, 51.51], geertz: [-87.63, 41.88], dumont: [2.35, 48.86],
    sahlins: [-87.63, 41.88], wolf: [-74.01, 40.71], mintz: [-76.61, 39.29],
    harris: [-74.01, 40.71], schneider: [-87.63, 41.88], bourdieu: [2.35, 48.86],
    rubin: [-83.74, 42.28], ortner: [-74.01, 40.71], "rosaldo-m": [-122.17, 37.43],
    taussig: [-74.01, 40.71], fabian: [4.90, 52.37], asad: [-0.34, 53.77],
    clifford: [-122.03, 36.97], marcus: [-95.37, 29.76], appadurai: [-87.63, 41.88],
    strathern: [0.12, 52.21], descola: [2.35, 48.86], viveiros: [-43.17, -22.91],
    latour: [2.35, 48.86], tsing: [-122.03, 36.97], "abu-lughod": [-74.01, 40.71],
    obeyesekere: [-74.66, 40.35], freeman: [149.13, -35.28], fei: [116.41, 39.90],
    lin: [116.41, 39.90], yan: [-118.24, 34.05], childe: [-3.19, 55.95],
    binford: [-106.65, 35.08], hodder: [0.12, 52.21], washburn: [-122.27, 37.87],
    montagu: [-74.66, 40.35], lewontin: [-71.11, 42.37], goodall: [0.12, 52.21],
    dewaal: [-84.39, 33.75], kleinman: [-71.06, 42.36]
  },

  cities: {
    "-74.01,40.71": "纽约", "0.12,52.21": "剑桥", "2.35,48.86": "巴黎", "-87.63,41.88": "芝加哥",
    "-1.26,51.75": "牛津", "-0.13,51.51": "伦敦", "-2.24,53.48": "曼彻斯特", "-122.03,36.97": "圣克鲁兹",
    "-74.66,40.35": "普林斯顿", "116.41,39.90": "北京", "13.40,52.52": "柏林", "-77.61,43.16": "罗切斯特",
    "-72.69,41.77": "哈特福德", "-76.61,39.29": "巴尔的摩", "-83.74,42.28": "安娜堡", "-122.17,37.43": "斯坦福",
    "4.90,52.37": "阿姆斯特丹", "-0.34,53.77": "赫尔", "-95.37,29.76": "休斯顿", "-43.17,-22.91": "里约热内卢",
    "149.13,-35.28": "堪培拉", "-118.24,34.05": "洛杉矶", "-3.19,55.95": "爱丁堡", "-106.65,35.08": "阿尔伯克基",
    "-122.27,37.87": "伯克利", "-71.11,42.37": "剑桥（麻省）", "-84.39,33.75": "亚特兰大", "-71.06,42.36": "波士顿"
  },

  sites: {
    bastian: [["秘鲁（考察）", -77.0, -12.0], ["东南亚（旅行考察）", 100.5, 13.7]],
    tylor: [["墨西哥（旅行考察）", -99.13, 19.43]],
    morgan: [["易洛魁领地（纽约州）", -76.4, 42.9]],
    frazer: [],
    boas: [["巴芬岛", -64.5, 66.0], ["夸扣特尔（温哥华岛）", -127.4, 50.6]],
    durkheim: [["澳大利亚原住民（文献研究）", 133.9, -23.7]],
    mauss: [["毛利与萨摩亚民族志（文献研究）", 172.0, -40.0]],
    malinowski: [["特罗布里恩德群岛", 150.7, -8.6]],
    "radcliffe-brown": [["安达曼群岛", 92.7, 12.5], ["西澳大利亚", 122.0, -25.0]],
    sapir: [["努特卡（温哥华岛）", -126.0, 50.0], ["黑脚（阿尔伯塔）", -113.0, 54.0]],
    mead: [["萨摩亚", -171.8, -14.0], ["阿德默勒尔蒂群岛", 147.0, -2.0], ["巴厘岛", 115.2, -8.4]],
    benedict: [["祖尼（普韦布洛）", -108.8, 35.1], ["日本（远距研究）", 139.7, 35.7]],
    whorf: [["霍皮人（美国西南）", -110.6, 35.9]],
    "evans-pritchard": [["阿赞德（苏丹南部）", 27.5, 5.0], ["努尔兰（南苏丹）", 32.0, 9.0]],
    firth: [["蒂科皮亚岛", 168.8, -12.3]],
    fortes: [["塔伦西（加纳北部）", -0.8, 10.7]],
    bateson: [["塞皮克河（新几内亚）", 143.5, -4.2], ["巴厘岛", 115.2, -8.4]],
    "levy-strauss": [["纳姆比克瓦拉/波洛罗（巴西内陆）", -56.0, -13.5]],
    leach: [["克钦山地（缅甸）", 97.5, 25.5], ["斯里兰卡（旱区）", 80.7, 7.9]],
    gluckman: [["祖鲁兰（南非）", 31.0, -28.5], ["巴罗策兰（赞比亚）", 23.1, -15.3]],
    turner: [["恩丹布（赞比亚）", 24.5, -11.5]],
    douglas: [["莱莱人（刚果）", 22.5, -5.0]],
    geertz: [["爪哇", 110.4, -7.5], ["巴厘岛", 115.2, -8.4], ["舍夫沙万（摩洛哥）", -5.27, 35.17]],
    dumont: [["南印度（泰米尔地区）", 78.5, 10.8]],
    sahlins: [["斐济", 178.4, -17.8], ["夏威夷", -157.9, 21.3], ["库克群岛", -159.8, -21.2]],
    wolf: [["瓦哈卡（墨西哥）", -96.7, 17.1], ["南蒂罗尔（阿尔卑斯）", 11.3, 46.5]],
    mintz: [["波多黎各", -66.5, 18.2], ["海地", -72.3, 18.5]],
    harris: [["巴伊亚（巴西）", -38.5, -13.0], ["莫桑比克", 35.0, -19.0], ["印度（文献研究）", 78.0, 20.0]],
    schneider: [["雅浦岛", 138.1, 9.5]],
    bourdieu: [["卡比利亚（阿尔及利亚）", 5.07, 36.75], ["贝阿恩（法国西南）", -0.37, 43.3]],
    rubin: [],
    ortner: [["昆布（尼泊尔）", 86.7, 27.8], ["夏威夷", -157.9, 21.3]],
    "rosaldo-m": [["伊隆戈（菲律宾吕宋）", 121.2, 16.5]],
    taussig: [["考卡河谷（哥伦比亚）", -76.5, 3.4]],
    fabian: [["加丹加（刚果）", 27.5, -10.5]],
    asad: [["卡巴比亚（苏丹）", 28.0, 15.6]],
    clifford: [],
    marcus: [["汤加", -175.2, -21.2]],
    appadurai: [["孟买", 72.9, 19.1], ["南印度（宗教研究）", 78.5, 10.8]],
    strathern: [["哈根山（巴布亚新几内亚）", 144.2, -5.85]],
    descola: [["阿丘雅（厄瓜多尔）", -77.9, -2.6]],
    viveiros: [["阿劳埃特（帕拉州）", -51.5, -5.0], ["上黑河（亚马逊）", -66.0, 0.5]],
    latour: [["阿比让（科特迪瓦）", -4.0, 6.8], ["索尔克研究所（拉霍亚）", -117.25, 32.85]],
    tsing: [["南加里曼丹（印尼）", 114.5, -2.5], ["俄勒冈森林", -122.7, 44.0]],
    "abu-lughod": [["西部沙漠（埃及贝都因）", 27.2, 31.35]],
    obeyesekere: [["康提（斯里兰卡）", 80.6, 7.3]],
    freeman: [["萨摩亚", -171.8, -14.0], ["沙捞越（伊班人）", 112.0, 2.0]],
    fei: [["开弦弓村（江苏吴江）", 120.6, 31.2], ["禄村（云南）", 102.0, 25.0]],
    lin: [["黄村（福建古田）", 118.7, 26.6], ["凉山（四川）", 102.3, 27.9]],
    yan: [["下岬村（黑龙江）", 126.5, 46.5]],
    childe: [["斯卡拉布雷（苏格兰）", -3.34, 59.05], ["近东新石器遗址（比较研究）", 43.0, 36.3]],
    binford: [["阿纳克图沃克山口（阿拉斯加）", -151.7, 68.1], ["多尔多涅（法国）", 0.9, 44.85]],
    hodder: [["恰塔霍裕克（土耳其）", 32.83, 37.67], ["伊尔查穆斯（肯尼亚）", 36.0, 0.3]],
    washburn: [["非洲（推动灵长类野外研究）", 36.0, -1.5]],
    montagu: [],
    lewontin: [],
    goodall: [["贡贝溪（坦桑尼亚）", 29.63, -4.67]],
    dewaal: [["伯格斯动物园（阿纳姆）", 5.9, 51.99], ["耶基斯田野站（亚特兰大）", -84.0, 33.9]],
    kleinman: [["台北", 121.5, 25.05], ["长沙（湖南医学院）", 113.0, 28.2]]
  },

  works: {
    "bastian-psychic": "Der Mensch in der Geschichte",
    "bastian-museum": "Museum für Völkerkunde, Berlin",
    "tylor-culture": "Primitive Culture", "tylor-animism": "Primitive Culture", "tylor-survivals": "Primitive Culture",
    "morgan-stages": "Ancient Society",
    "morgan-kinterms": "Systems of Consanguinity and Affinity of the Human Family",
    "morgan-iroquois": "League of the Ho-dé-no-sau-nee, or Iroquois",
    "frazer-goldengod": "The Golden Bough", "frazer-king": "The Golden Bough",
    "boas-relativism": "The Mind of Primitive Man",
    "boas-historism": "The Limitations of the Comparative Method of Anthropology",
    "boas-fieldwork": "The Methods of Ethnology",
    "boas-fourfields": "The History of Anthropology",
    "durkheim-rules": "Les Règles de la méthode sociologique",
    "durkheim-elementary": "Les Formes élémentaires de la vie religieuse",
    "mauss-gift": "Essai sur le don",
    "mauss-body": "Les Techniques du corps",
    "mauss-sacrifice": "Essai sur la nature et la fonction du sacrifice",
    "malinowski-method": "Argonauts of the Western Pacific",
    "malinowski-functionalism": "Argonauts of the Western Pacific",
    "malinowski-kula": "Argonauts of the Western Pacific",
    "malinowski-crime": "Crime and Custom in Savage Society",
    "radcliffe-brown-structure": "The Andaman Islanders",
    "radcliffe-brown-joking": "On Joking Relationships",
    "radcliffe-brown-function": "Structure and Function in Primitive Society",
    "sapir-language": "Language",
    "sapir-culture": "Culture, Genuine and Spurious",
    "mead-samoa": "Coming of Age in Samoa",
    "mead-gender": "Sex and Temperament in Three Primitive Societies",
    "benedict-patterns": "Patterns of Culture", "benedict-apollonian": "Patterns of Culture",
    "benedict-chrysanthemum": "The Chrysanthemum and the Sword",
    "whorf-relativity": "Science and Linguistics",
    "whorf-thought": "Languages and Logic",
    "evans-pritchard-witchcraft": "Witchcraft, Oracles and Magic among the Azande",
    "evans-pritchard-nuer": "The Nuer",
    "evans-pritchard-history": "Social Anthropology (Marett Lecture)",
    "firth-process": "We, the Tikopia",
    "firth-economy": "Primitive Polynesian Economy",
    "fortes-politics": "African Political Systems",
    "fortes-tallensi": "The Web of Kinship among the Tallensi",
    "bateson-schismogenesis": "Naven",
    "bateson-bali": "Balinese Character",
    "bateson-mind": "Steps to an Ecology of Mind",
    "levy-strauss-alliance": "Les Structures élémentaires de la parenté",
    "levy-strauss-tristes": "Tristes Tropiques",
    "levy-strauss-savage": "La Pensée sauvage",
    "levy-strauss-myth": "Mythologiques I: Le Cru et le cuit",
    "levy-strauss-race": "Race et histoire",
    "leach-burma": "Political Systems of Highland Burma",
    "leach-rethink": "Rethinking Anthropology",
    "gluckman-rebellion": "Rituals of Rebellion in South-East Africa",
    "gluckman-judicial": "The Judicial Process among the Barotse of Northern Rhodesia",
    "turner-ritual": "Schism and Continuity in an African Society",
    "turner-symbols": "The Forest of Symbols",
    "turner-communitas": "The Ritual Process",
    "douglas-purity": "Purity and Danger",
    "douglas-grid": "Natural Symbols",
    "geertz-interpretation": "The Interpretation of Cultures",
    "geertz-deep": "Deep Play: Notes on the Balinese Cockfight",
    "geertz-involution": "Agricultural Involution",
    "geertz-religion": "Religion as a Cultural System",
    "geertz-negara": "Negara: The Theatre State in Nineteenth-Century Bali",
    "dumont-homo": "Homo Hierarchicus", "dumont-ideology": "Homo Hierarchicus",
    "sahlins-affluent": "Stone Age Economics",
    "sahlins-practical-reason": "Culture and Practical Reason",
    "sahlins-islands": "Islands of History",
    "wolf-community": "Anthropology",
    "wolf-history": "Europe and the People Without History",
    "wolf-power": "Europe and the People Without History",
    "mintz-worker": "Worker in the Cane",
    "mintz-sugar": "Sweetness and Power", "mintz-commodity": "Sweetness and Power",
    "harris-theory": "The Rise of Anthropological Theory",
    "harris-materialism": "Cultural Materialism",
    "harris-cows": "Cows, Pigs, Wars and Witches",
    "schneider-american": "American Kinship: A Cultural Account",
    "schneider-critique": "A Critique of the Study of Kinship",
    "bourdieu-habitus": "Esquisse d'une théorie de la pratique",
    "bourdieu-distinction": "La Distinction",
    "rubin-traffic": "The Traffic in Women",
    "rubin-sex": "Thinking Sex",
    "ortner-nature": "Is Female to Male as Nature Is to Culture?",
    "ortner-practice": "Theory in Anthropology since the Sixties",
    "rosaldo-passion": "Knowledge and Passion",
    "rosaldo-feminism": "The Use and Abuse of Anthropology",
    "taussig-devil": "The Devil and Commodity Fetishism in South America",
    "taussig-mimesis": "Mimesis and Alterity",
    "fabian-time": "Time and the Other",
    "asad-encounter": "Anthropology and the Colonial Encounter",
    "asad-genealogy": "Genealogies of Religion",
    "clifford-authority": "On Ethnographic Authority",
    "clifford-predicament": "The Predicament of Culture",
    "marcus-multisited": "Ethnography in/of the World System",
    "marcus-authority": "Writing Culture",
    "appadurai-things": "The Social Life of Things",
    "appadurai-global": "Modernity at Large", "appadurai-imagined": "Modernity at Large",
    "strathern-gift": "The Gender of the Gift",
    "strathern-nature": "After Nature",
    "descola-ontology": "Par-delà nature et culture",
    "descola-naturalism": "Par-delà nature et culture",
    "viveiros-perspectivism": "Cosmological Deixis and Amerindian Perspectivism",
    "viveiros-multispecies": "Métaphysiques cannibales",
    "latour-lab": "Laboratory Life",
    "latour-modern": "Nous n'avons jamais été modernes",
    "latour-actors": "Pandora's Hope",
    "tsing-friction": "Friction",
    "tsing-mushroom": "The Mushroom at the End of the World",
    "abu-poetry": "Veiled Sentiments",
    "abu-writing": "Writing Against Culture",
    "obeyesekere-cook": "The Apotheosis of Captain Cook",
    "freeman-revisit": "Margaret Mead and Samoa: The Making and Unmaking of an Anthropological Myth",
    "fei-peasant": "Peasant Life in China",
    "fei-chaxu": "From the Soil", "fei-ritual": "From the Soil",
    "fei-multiunity": "The Plurality and Unity of the Chinese Nation",
    "lin-golden": "The Golden Wing",
    "lin-lolo": "The Lolo of Liang Shan",
    "yan-gift": "The Flow of Gifts",
    "yan-private": "Private Life under Socialism",
    "childe-neolithic": "Man Makes Himself",
    "childe-culturehistory": "The Dawn of European Civilization",
    "binford-science": "Archaeology as Anthropology",
    "binford-midrange": "For Theory Building in Archaeology",
    "hodder-symbolic": "Symbols in Action",
    "hodder-reading": "Reading the Past",
    "washburn-newphys": "The New Physical Anthropology",
    "washburn-primate": "The New Physical Anthropology",
    "montagu-myth": "Man's Most Dangerous Myth: The Fallacy of Race",
    "montagu-unesco": "UNESCO Statement on Race",
    "lewontin-apportionment": "The Apportionment of Human Diversity",
    "lewontin-genes": "Not in Our Genes",
    "goodall-tools": "In the Shadow of Man",
    "goodall-gombe": "The Chimpanzees of Gombe",
    "dewaal-politics": "Chimpanzee Politics",
    "dewaal-morality": "Good Natured",
    "kleinman-models": "Patients and Healers in the Context of Culture",
    "kleinman-narratives": "The Illness Narratives"
  }
};
